//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_PPA_Amount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BP_PPA_Amount()
        {
            this.BPAIP_PPAperOffice = new HashSet<BPAIP_PPAperOffice>();
        }
    
        public int PPACCCostID { get; set; }
        public string PS { get; set; }
        public string CO { get; set; }
        public string MOOE { get; set; }
        public string OFExpense { get; set; }
        public string PPATotal { get; set; }
        public string CCAdoptation { get; set; }
        public string CCMitigation { get; set; }
        public string CCTypologyCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPAIP_PPAperOffice> BPAIP_PPAperOffice { get; set; }
    }
}
