//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPAIP_PPAperOffice
    {
        public int ProgramID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string BudgetYear { get; set; }
        public Nullable<bool> isInfrastructure { get; set; }
        public string AIPCode { get; set; }
        public string ProgDescription { get; set; }
        public string ProgType { get; set; }
        public Nullable<int> FundID { get; set; }
        public Nullable<System.DateTime> ProgStartDate { get; set; }
        public Nullable<System.DateTime> ProgCompletionDate { get; set; }
        public string ProgPolicyObjective { get; set; }
        public string ExpectedOutput { get; set; }
        public string ProgOImplementingOffice { get; set; }
        public Nullable<int> SubSectorID { get; set; }
        public Nullable<int> PPACCCostID { get; set; }
    
        public virtual BP_PPA_Amount BP_PPA_Amount { get; set; }
        public virtual Tbl_FMFund_Fund Tbl_FMFund_Fund { get; set; }
        public virtual Tbl_FMRes_Department Tbl_FMRes_Department { get; set; }
        public virtual Tbl_FMSector_SubSector Tbl_FMSector_SubSector { get; set; }
    }
}
