//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FundSource()
        {
            this.Tbl_FMAppropriationSource = new HashSet<Tbl_FMAppropriationSource>();
        }
    
        public int FundSourceID { get; set; }
        public string FundSourceTitle { get; set; }
        public Nullable<int> AppropriationSourceID { get; set; }
    
        public virtual AppropriationSourceType AppropriationSourceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMAppropriationSource> Tbl_FMAppropriationSource { get; set; }
    }
}
