//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level1Modules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Level1Modules()
        {
            this.Level2Modules = new HashSet<Level2Modules>();
        }
    
        public int Level1ModuleID { get; set; }
        public string Level1ModuleName { get; set; }
        public Nullable<int> ModuleParentID { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string JSID { get; set; }
    
        public virtual ParentModule ParentModule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Level2Modules> Level2Modules { get; set; }
    }
}
