//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level3Modules
    {
        public int Level3ModuleID { get; set; }
        public string Level3ModuleName { get; set; }
        public Nullable<int> Level2ModuleID { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string JSID { get; set; }
    
        public virtual Level2Modules Level2Modules { get; set; }
    }
}
