//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeType
    {
        public int OfficeTypeID { get; set; }
        public string OfficeTypeTitle { get; set; }
        public string OfficeTypeCode { get; set; }
    }
}
