//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMApprop_FundSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMApprop_FundSource()
        {
            this.Tbl_FMApprop_AppropriationSource = new HashSet<Tbl_FMApprop_AppropriationSource>();
        }
    
        public int FundSourceID { get; set; }
        public string FundSourceTitle { get; set; }
        public Nullable<int> AppropSourceTypeID { get; set; }
    
        public virtual FMApprop_AppropriationSourceType FMApprop_AppropriationSourceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMApprop_AppropriationSource> Tbl_FMApprop_AppropriationSource { get; set; }
    }
}
