//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMCOA_MajorAccountGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMCOA_MajorAccountGroup()
        {
            this.Tbl_FMCOA_SubMajorAccountGroup = new HashSet<Tbl_FMCOA_SubMajorAccountGroup>();
        }
    
        public int MAGID { get; set; }
        public string MAGTitle { get; set; }
        public string MAGCode { get; set; }
        public Nullable<int> AGID { get; set; }
    
        public virtual Tbl_FMCOA_AccountGroup Tbl_FMCOA_AccountGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMCOA_SubMajorAccountGroup> Tbl_FMCOA_SubMajorAccountGroup { get; set; }
    }
}
