//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FMCOA_SubLedger_SLAccnt
    {
        public int SLAccntID { get; set; }
        public string SLAccntTitle { get; set; }
        public string SLAccntCode { get; set; }
        public string SLAccntCategory { get; set; }
        public Nullable<int> SLAccntCatDescription { get; set; }
        public Nullable<int> SLClassID { get; set; }
    
        public virtual TBL_FMCOA_SubLedger_SLClass TBL_FMCOA_SubLedger_SLClass { get; set; }
    }
}
