//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMRevisionOfCOA
    {
        public int RevID { get; set; }
        public Nullable<int> RevYEar { get; set; }
        public Nullable<bool> isUsed { get; set; }
        public string Remarks { get; set; }
    }
}
