//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMMajorAccountGroup
    {
        public int MAGID { get; set; }
        public string MAGTitle { get; set; }
        public string MAGCode { get; set; }
        public Nullable<int> AGID { get; set; }
    
        public virtual Tbl_FMAccountGroup Tbl_FMAccountGroup { get; set; }
    }
}
