//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMBrgy_BrgyBankAccount
    {
        public int BrgyBankAccntID { get; set; }
        public Nullable<int> BrgyID { get; set; }
        public Nullable<int> BankAccntID { get; set; }
    
        public virtual Tbl_FMBank_BankAccounts Tbl_FMBank_BankAccounts { get; set; }
        public virtual Tbl_FMBrgy_Barangay Tbl_FMBrgy_Barangay { get; set; }
    }
}
