//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMCOA_GeneralAccount
    {
        public int GAID { get; set; }
        public Nullable<int> RevID { get; set; }
        public Nullable<int> SMAGID { get; set; }
        public string GATitle { get; set; }
        public string GACode { get; set; }
        public Nullable<bool> isReserve { get; set; }
        public Nullable<int> ReservePercent { get; set; }
        public Nullable<bool> isFullRelease { get; set; }
        public Nullable<bool> isContinuing { get; set; }
        public Nullable<bool> isOBRCashAdvance { get; set; }
        public Nullable<int> BalanceID { get; set; }
        public Nullable<bool> isMiscellaneousAccount { get; set; }
        public Nullable<int> GAIDMA { get; set; }
        public Nullable<bool> isContraAccount { get; set; }
        public Nullable<int> GAIDCA { get; set; }
        public Nullable<bool> isSubAccount { get; set; }
        public Nullable<int> GAIDSA { get; set; }
    }
}
