//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMFunction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMFunction()
        {
            this.Tbl_FMSection = new HashSet<Tbl_FMSection>();
            this.Tbl_FMSignatory = new HashSet<Tbl_FMSignatory>();
        }
    
        public int FunctionID { get; set; }
        public string FunctionTitle { get; set; }
        public string FunctionAbbrv { get; set; }
        public string FunctionCode { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> SubSectorID { get; set; }
        public Nullable<int> OfficeTypeID { get; set; }
        public string DeptOfficeCodefunc { get; set; }
        public Nullable<int> DeptID { get; set; }
    
        public virtual Tbl_FMDepartment Tbl_FMDepartment { get; set; }
        public virtual Tbl_FMOfficeType Tbl_FMOfficeType { get; set; }
        public virtual Tbl_FMSector Tbl_FMSector { get; set; }
        public virtual Tbl_FMSubSector Tbl_FMSubSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMSection> Tbl_FMSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMSignatory> Tbl_FMSignatory { get; set; }
    }
}
