//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FMCOA_SubLedger_SLClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_FMCOA_SubLedger_SLClass()
        {
            this.TBL_FMCOA_SubLedger_SLAccnt = new HashSet<TBL_FMCOA_SubLedger_SLAccnt>();
        }
    
        public int SLClassID { get; set; }
        public string SLClassTitle { get; set; }
        public string SLClassCode { get; set; }
        public Nullable<int> FundID { get; set; }
        public Nullable<int> GAID { get; set; }
    
        public virtual Tbl_FMCOA_GeneralAccount Tbl_FMCOA_GeneralAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FMCOA_SubLedger_SLAccnt> TBL_FMCOA_SubLedger_SLAccnt { get; set; }
        public virtual Tbl_FMFund_Fund Tbl_FMFund_Fund { get; set; }
    }
}
