//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMSector_SubSector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMSector_SubSector()
        {
            this.Tbl_FMRes_Department = new HashSet<Tbl_FMRes_Department>();
            this.Tbl_FMRes_Function = new HashSet<Tbl_FMRes_Function>();
        }
    
        public int SubSectorID { get; set; }
        public string SubSectorTitle { get; set; }
        public string SubSectorCode { get; set; }
        public Nullable<int> SectorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMRes_Department> Tbl_FMRes_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMRes_Function> Tbl_FMRes_Function { get; set; }
        public virtual Tbl_FMSector_Sector Tbl_FMSector_Sector { get; set; }
    }
}
