//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMRes_Section
    {
        public int SectionID { get; set; }
        public string SectionTitle { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> FunctionID { get; set; }
    
        public virtual Tbl_FMRes_Department Tbl_FMRes_Department { get; set; }
        public virtual Tbl_FMRes_Function Tbl_FMRes_Function { get; set; }
    }
}
