//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMCOA_SubMajorAccountGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMCOA_SubMajorAccountGroup()
        {
            this.Tbl_FMCOA_GeneralAccount = new HashSet<Tbl_FMCOA_GeneralAccount>();
        }
    
        public int SMAGID { get; set; }
        public string SMAGTitle { get; set; }
        public string SMAGCode { get; set; }
        public Nullable<int> MAGID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMCOA_GeneralAccount> Tbl_FMCOA_GeneralAccount { get; set; }
        public virtual Tbl_FMCOA_MajorAccountGroup Tbl_FMCOA_MajorAccountGroup { get; set; }
    }
}
