//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMRes_Function
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMRes_Function()
        {
            this.Tbl_FMRes_Section = new HashSet<Tbl_FMRes_Section>();
            this.Tbl_FMSignatory = new HashSet<Tbl_FMSignatory>();
        }
    
        public int FunctionID { get; set; }
        public string FunctionTitle { get; set; }
        public string FunctionAbbrv { get; set; }
        public string FunctionCode { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> SubSectorID { get; set; }
        public Nullable<int> OfficeTypeID { get; set; }
        public string DeptOfficeCodefunc { get; set; }
        public Nullable<int> DeptID { get; set; }
    
        public virtual Tbl_FMOfficeType Tbl_FMOfficeType { get; set; }
        public virtual Tbl_FMRes_Department Tbl_FMRes_Department { get; set; }
        public virtual Tbl_FMSector_Sector Tbl_FMSector_Sector { get; set; }
        public virtual Tbl_FMSector_SubSector Tbl_FMSector_SubSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMRes_Section> Tbl_FMRes_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMSignatory> Tbl_FMSignatory { get; set; }
    }
}
