//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMCOA_AllotmentClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMCOA_AllotmentClass()
        {
            this.Tbl_FMCOA_AccountGroup = new HashSet<Tbl_FMCOA_AccountGroup>();
        }
    
        public int AllotmentClassID { get; set; }
        public string AllotmentClassTitle { get; set; }
        public Nullable<int> RevID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMCOA_AccountGroup> Tbl_FMCOA_AccountGroup { get; set; }
        public virtual Tbl_FMCOA_RevisionYear Tbl_FMCOA_RevisionYear { get; set; }
    }
}
