//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMSubAccount
    {
        public int SubAccountID { get; set; }
        public string SubAccountCode { get; set; }
        public string SubAccountTitle { get; set; }
        public Nullable<bool> isReserve { get; set; }
        public Nullable<int> ReservePercent { get; set; }
        public Nullable<bool> isFullRelease { get; set; }
        public Nullable<bool> isContinuing { get; set; }
        public Nullable<bool> isOBRCashAdvance { get; set; }
        public Nullable<int> GenAccountID { get; set; }
        public Nullable<int> AllotmentID { get; set; }
    
        public virtual AllotmentClass AllotmentClass { get; set; }
        public virtual Tbl_FMGeneralAccount Tbl_FMGeneralAccount { get; set; }
    }
}
