//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMSubMajorAccountGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMSubMajorAccountGroup()
        {
            this.Tbl_FMGeneralAccount = new HashSet<Tbl_FMGeneralAccount>();
        }
    
        public int SMAGID { get; set; }
        public string SMAGTitle { get; set; }
        public string SMAGCode { get; set; }
        public Nullable<int> MAGID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMGeneralAccount> Tbl_FMGeneralAccount { get; set; }
        public virtual Tbl_FMMajorAccountGroup Tbl_FMMajorAccountGroup { get; set; }
    }
}
