//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMFund_Fund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMFund_Fund()
        {
            this.BPAIP_PPAperOffice = new HashSet<BPAIP_PPAperOffice>();
            this.Tbl_FMBank_BankAccounts = new HashSet<Tbl_FMBank_BankAccounts>();
            this.TBL_FMCOA_SubLedger_SLClass = new HashSet<TBL_FMCOA_SubLedger_SLClass>();
            this.Tbl_FMFund_SubFund = new HashSet<Tbl_FMFund_SubFund>();
            this.Tbl_FMRes_Department = new HashSet<Tbl_FMRes_Department>();
        }
    
        public int FundID { get; set; }
        public string FundTitle { get; set; }
        public string FundCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPAIP_PPAperOffice> BPAIP_PPAperOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMBank_BankAccounts> Tbl_FMBank_BankAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FMCOA_SubLedger_SLClass> TBL_FMCOA_SubLedger_SLClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMFund_SubFund> Tbl_FMFund_SubFund { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMRes_Department> Tbl_FMRes_Department { get; set; }
    }
}
