//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMCOA_GeneralAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMCOA_GeneralAccount()
        {
            this.Tbl_FMBank_BankAccounts = new HashSet<Tbl_FMBank_BankAccounts>();
            this.TBL_FMCOA_SubLedger_SLClass = new HashSet<TBL_FMCOA_SubLedger_SLClass>();
            this.Tbl_FMTax = new HashSet<Tbl_FMTax>();
        }
    
        public int GAID { get; set; }
        public Nullable<int> SMAGID { get; set; }
        public string GATitle { get; set; }
        public string GACode { get; set; }
        public Nullable<bool> isReserve { get; set; }
        public string ReservePercent { get; set; }
        public Nullable<bool> isFullRelease { get; set; }
        public Nullable<bool> isContinuing { get; set; }
        public Nullable<bool> isOBRCashAdvance { get; set; }
        public string NormalBalance { get; set; }
        public Nullable<int> isMiscellaneousAccount { get; set; }
        public Nullable<int> isContraAccount { get; set; }
        public Nullable<int> isSubAccount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMBank_BankAccounts> Tbl_FMBank_BankAccounts { get; set; }
        public virtual Tbl_FMCOA_SubMajorAccountGroup Tbl_FMCOA_SubMajorAccountGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FMCOA_SubLedger_SLClass> TBL_FMCOA_SubLedger_SLClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMTax> Tbl_FMTax { get; set; }
    }
}
