//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMAccountGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMAccountGroup()
        {
            this.Tbl_FMMajorAccountGroup = new HashSet<Tbl_FMMajorAccountGroup>();
        }
    
        public int AGID { get; set; }
        public string AGTitle { get; set; }
        public string AGCode { get; set; }
        public Nullable<int> AllotmentClassID { get; set; }
    
        public virtual Tbl_FMAllotmentClass Tbl_FMAllotmentClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMMajorAccountGroup> Tbl_FMMajorAccountGroup { get; set; }
    }
}
