//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMPosition
    {
        public int PositionID { get; set; }
        public string PositionTitle { get; set; }
        public Nullable<int> PSID { get; set; }
        public Nullable<int> PCID { get; set; }
    
        public virtual PositionClassification PositionClassification { get; set; }
        public virtual PositionStatu PositionStatu { get; set; }
    }
}
