//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMBank_BankAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMBank_BankAccounts()
        {
            this.Tbl_FMBrgy_BrgyBankAccount = new HashSet<Tbl_FMBrgy_BrgyBankAccount>();
        }
    
        public int BankAccntID { get; set; }
        public string AccntNo { get; set; }
        public string AccntName { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> FundID { get; set; }
        public Nullable<int> GAID { get; set; }
        public Nullable<int> AccntTypeID { get; set; }
    
        public virtual Tbl_FMBank_AccountType Tbl_FMBank_AccountType { get; set; }
        public virtual Tbl_FMBank_Banks Tbl_FMBank_Banks { get; set; }
        public virtual Tbl_FMCOA_GeneralAccount Tbl_FMCOA_GeneralAccount { get; set; }
        public virtual Tbl_FMFund_Fund Tbl_FMFund_Fund { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMBrgy_BrgyBankAccount> Tbl_FMBrgy_BrgyBankAccount { get; set; }
    }
}
