//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMSupplier
    {
        public int SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string ProductServices { get; set; }
        public string Address { get; set; }
        public string TaxType { get; set; }
        public string DTIRegNo { get; set; }
        public string CDARegistry { get; set; }
        public string FaxNo { get; set; }
        public string TelNo { get; set; }
        public string TIN { get; set; }
        public string MFName { get; set; }
        public string MFAddress { get; set; }
        public string MFContactNo { get; set; }
        public string AccreNumber { get; set; }
        public string AccreDate { get; set; }
        public string AccreValidUntil { get; set; }
        public string AccreApproveBy { get; set; }
        public string AccreMOA { get; set; }
    }
}
