//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMFunction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMFunction()
        {
            this.Tbl_FMOfficeSection = new HashSet<Tbl_FMOfficeSection>();
        }
    
        public int FunctionID { get; set; }
        public string FunctionTitle { get; set; }
        public string FunctionAbbrv { get; set; }
        public string FunctionCode { get; set; }
        public Nullable<int> FundID { get; set; }
        public Nullable<int> DeptID { get; set; }
    
        public virtual FundType FundType { get; set; }
        public virtual Tbl_FMDepartment Tbl_FMDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMOfficeSection> Tbl_FMOfficeSection { get; set; }
    }
}
