//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FMBank_Banks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FMBank_Banks()
        {
            this.Tbl_FMBank_BankAccounts = new HashSet<Tbl_FMBank_BankAccounts>();
        }
    
        public int BankID { get; set; }
        public string BankTitle { get; set; }
        public string BankCode { get; set; }
        public string BankAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FMBank_BankAccounts> Tbl_FMBank_BankAccounts { get; set; }
    }
}
